### PR TITLE
migrated to circleci 2 and gradle wrapper

### PR DESCRIPTION
**Pull request by nickalie**

### CODE REVIEW

**Comment by Egis-Kevin** [comment]
@nickalie Let me know when this can be merged?

**Comment by nickalie** [comment]
@Egis-Kevin ready to merge

**Comment by Egis-Kevin** [comment]
@nickalie These changes won't hurt Bootstrapped project using Gradle? Utils modules etc?

**Comment by nickalie** [comment]
The major change here - I removed jetty 6 dependencies. So if some modules relies on it, they need to be migrated to Jetty 9 as well.

**Comment by nickalie** [comment]
@Egis-Kevin plus it's still would be possible to use previous version of gradle-build from gradle repository.

**Pull request merged**
